name: Benchmark
concurrency: ${{github.ref_name}}
on: 
  schedule:
    - cron: '13 * * * *'
  workflow_dispatch:
    
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      config: ${{ steps.read_touchstone_config.outputs.config }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
           fetch-depth: 0

      - id: read_touchstone_config
        run: |
          content=`cat ./touchstone/config.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=config::$content"
  benchmark:
    needs: prepare
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - ${{ fromJson(needs.prepare.outputs.config) }}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
           fetch-depth: 0
      - name: Set up git user
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
      - name: Ensure base branch is fetched
        run: |
          git checkout -b feature # this is current ref. This is required for naming.
      - name: Setup R
        uses: r-lib/actions/setup-r@master
      - name: Setup dependencies
        uses: r-lib/actions/setup-r-dependencies@7b33c047b62e312480dccff128409e7cf92e2460
        with:
          cache-version: 1
          extra-packages: |
            assignUser/touchstone
            ggplot2
            dplyr
            gert
      - name: Remove global installation
        run: | 
          pkg <- basename(getwd())
          if (pkg %in% rownames(installed.packages())) {
            remove.packages(pkg)
            cat('removed package ', pkg, '.', sep = "")
          }
        shell: Rscript {0}
      - name: Create dir
        run: |
          now=$(date +%s)
          mkdir $now
          echo $now > now
      - name: Run benchmarks
        run: Rscript -e 'touchstone::activate("feature", "main"); touchstone::run_script("touchstone/script.R")'
      - name: Move records
        run: |
          now=$(cat now)
          mv touchstone/records/* $now/
      - uses: actions/upload-artifact@v2
        with:
          name: data
          path: 16*
  save:
    needs: benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
           ref: data
      - name: Set up git user
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
      - name: Download data
        uses: actions/download-artifact@v2
        with:
          name: data
      - name: push
        run: |
          git add .
          git commit -m"add data"
          git push
        

