name: test

on: workflow_dispatch

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Get
        run: |
          now=$(date +%s) 
          mkdir $now
          cd $now
          wget https://www.wikidata.org/wiki/Special:EntityData/Q42.json
      - uses: actions/upload-artifact@v2
        with:
          name: data
          path: 16*
  save:
    needs: fetch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
           ref: data
      - name: Set up git user
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
      - name: Download data
        uses: actions/download-artifact@v2
        with:
          name: data
      # - name: prepare
      #   run: |
      #     unzip data
      #     rm data.zip
      - name: push
        run: |
          git add .
          git commit -m"add data"
          git push
        

